### ISSUE TITLE
Touble forking this repo to submit pull requests

### ISSUE THREAD

**Issue by camfindlay** [studiobonito/silverstripe-google-analytics#2]
Unsure why... but I've not been able to fork or raise PRs against this repo. Can you see if there are any settings or maybe contact GitHub help?

In the meantime, can you update your composer.json to allow use of this in SilverStripe core 3.3.x? Thanks :)

**Comment by nedmas** [comment]
Hey @camfindlay we had both master/develop branches marked as protected which might have been causing the issue with forking. Not sure why though? I've disabled that for the time being.

I've been intending to update all our modules to be less restrictive in their requirements, should get time to do this on Friday. But feel free to try submitting a PR again in the mean time.

**Comment by camfindlay** [comment]
Strange, when I try to raise an edit and PR via GitHub UI I cannot and see the follow error:

![screen shot 2016-04-28 at 10 48 46 am](https://cloud.githubusercontent.com/assets/367847/14870522/eaf07ca2-0d2e-11e6-9569-9f525d53e3e2.png)

Might need to ping GH about this?

**Comment by camfindlay** [comment]
Ok... seems to have been an over enthusiastic ad popup blocker chrome extension causing all the issues. Crazy!
